version: '3.8'
services:
  wordpress_db:
    image: mysql:8.0
    container_name: wordpress_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root_password
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD_FILE: /run/secrets/mysql_password
    networks:
      - backend
    volumes:
      - db_data:/var/lib/mysql
    secrets:
      - mysql_root_password
      - mysql_password

  wordpress:
    depends_on:
      - wordpress_db
    image: wordpress:latest
    container_name: wordpress
    restart: always
    environment:
      WORDPRESS_DB_HOST: wordpress_db:3306
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD_FILE: /run/secrets/wordpress_db_password
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
    networks:
      - backend
      - frontend
    volumes:
      - wp_data:/var/www/html
    secrets:
      - wordpress_db_password

networks:
  frontend:
  backend:

volumes:
  db_data:
  wp_data:

secrets:
  mysql_root_password:
    file: .mysql_root_password
  mysql_password:
    file: .mysql_password
  wordpress_db_password:
    file: .wordpress_db_password
